[general]
resolution = [480, 832]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = true

[[datasets]]
image_directory = "/workspace/dataset"
cache_directory = "/workspace/cache/latents"
num_repeats = 1
